### PR TITLE
Add Backglass toggle

### PR DESCRIPTION
**Pull request by stevejones72**
https://github.com/vpinball/b2s-backglass/issues/80

### CODE REVIEW

**Comment by stevejones72** [comment]
Just a note, I updated only the .exe version of the code for now. I'm tempted to work on getting the two codebases into one, but fear that rabbit hole when first looking into a codebase.

**Comment by jsm174** [comment]
yeh, its definitely confusing with the two code bases. 😄

When I ported to C++, it's more based on the `b2sbackglassserver` version (we don't have a registry on cross platform standalone)

**Comment by JockeJarre** [comment]
I think the merge is more or less finished in the branch (mostly features of the brought back to the dll)
So yes, please leave the exe behind and let's get only one codebase finally.
I will do a last check tomorrow when I am home from vacation.

**Comment by stevejones72** [comment]
Thanks JockeJarre, I'll 
I have a local version running as an .exe of a quick wrapper that brings in the .dll, that might help with the single codebase. I'm also halfway through building out the .zip container implementation, brings a ~32Mb .directb2s file down to a  ~22Mb .directb2sc file size.

**Comment by stevejones72** [comment]
Will wait for updates to .dll and will create a PR from that.

**Review by JockeJarre — COMMENTED** [review]
looks good

**Comment by stevejones72** [comment]
Sorry. I closed this PR before I saw your comment, I was waiting to see when your merge of features between the two codebases landed.

**Comment by JockeJarre** [comment]
No problem... the merge is done, though depending on how your wrapper works we might need to do some more things. That the code can sense how it is started and acts either as dll or exe earlier did.

**Comment by JockeJarre** [comment]
And your PR was mixing topics "checkbox for backglass" could come in separate already now.

**Comment by stevejones72** [comment]
On a totally different topic:

I try building vpinball, and when I go to edit a dialog box I get the following:

[cid:3eb6f822-eb7a-420c-833a-bdc438083fa8]

I noticed you changed that file a little while ago, is this something specific with my tooling? I'm using VS2022 professional.

Thanks,

Steve

________________________________

**Pull request closed without merging**
